
version: "3.6"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/sirius-workflow/Dockerfile
    ports: ["8888:1234"]

    environment:
      SIRIUS_URL: http://pact-stub:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080

  pact-stub:
    build: ./pact-stub
    environment:
      PACT_DIR: ./pacts
      PORT: 8080
    volumes:
      - "../pacts:/app/pacts"