name: Create Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "Semver Tag (the latest tag on a workflow dispatch)"
        value: ${{ jobs.create_tag.outputs.tag }}
      timestamp:
        description: "timestamp"
        value: ${{ jobs.create_tag.outputs.timestamp }}

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: '0'

      - name: "Generate semver tag and release"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/actions/semver@82323da6c533ab565c1652a590230ff2f0acc942 # v4.3.8
        with:
          create_release: false
          default_bump: ${{ github.event_name == 'workflow_dispatch' && 'none' || 'minor' }}
          prerelease: ${{ github.ref_name == 'main' && 'false' || 'true' }}

      - name: Set Timestamp
        id: timestamp
        run: echo "timestamp=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
    outputs:
      tag: ${{ steps.semver_tag.outputs.tag }}
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
