name: Create Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "Semver Tag (the latest tag on a workflow dispatch)"
        value: ${{ jobs.create_tag.outputs.tag }}
      timestamp:
        description: "timestamp"
        value: ${{ jobs.create_tag.outputs.timestamp }}

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: '0'

      - name: "Generate semver tag and release"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/actions/semver@e3177e63e9f2951dd3f1f7c7aa093918a5a0794a # v4.3.6
        with:
          create_release: false
          default_bump: ${{ github.event_name == 'workflow_dispatch' && 'none' || 'minor' }}
          prerelease: ${{ github.ref_name == 'main' && 'false' || 'true' }}

      - name: Set Timestamp
        id: timestamp
        run: echo "timestamp=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
    outputs:
      tag: ${{ steps.semver_tag.outputs.tag }}
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
